### ISSUE TITLE
$mq

### ISSUE THREAD

**Issue by skrappyzz** [liquidlight/sass-gulp-svg-sprite#1]
Hi, you forgot to include _mq.scss.
And it would be better if gulp-sass has been included into the gulpfile.js. Thx.

**Comment by mikestreety** [comment]
Not sure what you mean? All the media query stuff is located in the `mixins` file.

This repo purely focusses on the sprite - it's up to you if you want to use `gulp-sass` or `gulp-node-sass` or `post-css` etc. This is not meant to be a working example, purely an example of how to use glup-svg-sprite.
