### ISSUE TITLE
PNG Sprite Fails to Generate

### ISSUE THREAD

**Issue by lupinskij** [liquidlight/sass-gulp-svg-sprite#3]
Seems to be an issues with `verbose: true` as it's generating just a blank png. 

```
.pipe($.svg2png({
  verbose: true
}))
```

In addition, it seems the png dest is a level to high

**Comment by mikestreety** [comment]
Hi @lupinskij - thanks for pointing that out. 

Have you managed to get it working? :smile:

**Comment by mikestreety** [comment]
Thanks @lupinskij - resolved and pushed a fix.
