### ISSUE TITLE
Error in plugin ‘gulp-svg-sprite’

### ISSUE THREAD

**Issue by racinggrinner** [liquidlight/sass-gulp-svg-sprite#5]
When adding a new svg to an existing project I am getting the following error:

```
File build/sprite/icon—download-purple.svg was added
starting ‘svgSprite’…
File build/sprite/icon—download-purple.svg was changed
‘svgSprite’ error after 193 ms
Error in plugin ‘gulp-svg-sprite’
Message:
Skipping “%s” (%s)
```
The svg is a direct copy of an existing svg from the project which was previously successfully 'sprited' (Eliminating possibility of corrupt svg). Something else has changed causing this error... Any clues?

I'm using a MAC / Node / NPM

This could be related to:
https://github.com/jkphl/gulp-svg-sprite/issues/48

**Comment by mikestreety** [comment]
Hmm, interesting. Are you able to isolate and upload a zip of the files?

**Comment by racinggrinner** [comment]
Sure you can download the zip located here:
https://www.drupal.org/project/sector
And navigate to the theme folder: 
http://cgit.drupalcode.org/sector/tree/themes/contrib/sector_starter
This repo does not contain the test icon—download-purple.svg but is the same code base where I received the error. Thanks.

**Comment by mikestreety** [comment]
Thanks, I'll have a look tomorrow and see if I can locate the problem.

It might be a permissions issue, so if you get a chance to check before
I've had a look, double check the read/write/group 🙂

**Comment by racinggrinner** [comment]
Thanks Mike, Yes permissions are an area I've looked at. It seems that the target ../../scss/generic/_sprite.scss is not being re/written...

**Comment by mikestreety** [comment]
Hi @racinggrinner,

I've had a quick look this morning and there are a few different issues here (I didn't manage to get the `skipping %` but I have seen it before.

To make the sprite override:

1. Make sure all your paths in the file are up to date. I have to change a few to get the expected result. All the paths are relative to the `gulpfile` (you have a few `../../` which will make it two folders _above_ the gulpfile
2. The main reason your sprite wasn't being overwritten was that the `sprite` task doesn't have a [destination pipe](https://github.com/liquidlight/sass-gulp-svg-sprite/blob/master/gulpfile.js#L62) - this is crucial. Despite the plugin itself having paths the main sprite image needs to know where to go.

Let me know how you get on.

**Comment by racinggrinner** [comment]
Ah ha thanks Mike... look what I found in a recent commit... Thanks for the code review! I'll be chatting to my colleague later! http://cgit.drupalcode.org/sector/commit/?id=9619cad19fb2c4c369be62cba06a03a2c574b2ec

```
-    }))
-    .pipe(gulp.dest(basePaths.dest));
+    }));
 });
```

**Comment by mikestreety** [comment]
Haha! Let me know how you get on

**Comment by mikestreety** [comment]
How did you get on @racinggrinner?

**Comment by racinggrinner** [comment]
Hi Mike, Sorry for the delay, I've been away on leave for a few weeks. The chat went well. He has his tail between his legs now! Never remove something you don't understand! Thanks again.

**Comment by SultanMashukov** [comment]
Check encodings of your svg files. I had UTF-16 encoding in one file. After saving it to UTF-8, it worked!

**Comment by Kirill222** [comment]
In my case this was caused by svg file. Something wrong with it. Downloaded another svg and everything worked
